version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "wp_2024_events"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Simba&05
      - POSTGRES_DB=events
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data